<h1> Cross-fold Validation <h1>

<b>K fold Cross Validation<b>

In [47]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [49]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [50]:
Cancer = pd.read_csv('Prostate_Cancer2.csv')

In [51]:
Cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    object 
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [52]:
Cancer.head(10)

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   
5   6                B      25       25         83   477       0.128   
6   7                M      16       26        120  1040       0.095   
7   8                M      15       18         90   578       0.119   
8   9                M      19       24         88   520       0.127   
9  10                M      25       11         84   476       0.119   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059  
5        0.170     0.209              0.076  
6        0.109     0.179              0.057  
7        0.165     0.220              0.075  
8        0.193     0.235              0.074  
9        0.240     0.203              0.082

In [53]:
Cancer.describe()

id      radius     texture   perimeter         area  \
count  100.000000  100.000000  100.000000  100.000000   100.000000   
mean    50.500000   16.850000   18.230000   96.780000   702.880000   
std     29.011492    4.879094    5.192954   23.676089   319.710895   
min      1.000000    9.000000   11.000000   52.000000   202.000000   
25%     25.750000   12.000000   14.000000   82.500000   476.750000   
50%     50.500000   17.000000   17.500000   94.000000   644.000000   
75%     75.250000   21.000000   22.250000  114.250000   917.000000   
max    100.000000   25.000000   27.000000  172.000000  1878.000000   

       smoothness  compactness    symmetry  fractal_dimension  
count  100.000000   100.000000  100.000000         100.000000  
mean     0.102730     0.126700    0.193170           0.064690  
std      0.014642     0.061144    0.030785           0.008151  
min      0.070000     0.038000    0.135000           0.053000  
25%      0.093500     0.080500    0.172000           0.059000  
50%      0.102000     0.118500    0.190000           0.063000  
75%      0.112000     0.157000    0.209000           0.069000  
max      0.143000     0.345000    0.304000           0.097000

In [54]:
Cancer.diagnosis_result = [1 if each == 'M' else 0 for each in Cancer.diagnosis_result]

In [55]:
Cancer.diagnosis_result.value_counts()

1    62
0    38
Name: diagnosis_result, dtype: int64

In [56]:
y = Cancer.diagnosis_result.values
x_data = Cancer.drop(['diagnosis_result'],axis=1)

In [57]:
y

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [58]:
x_data.head()

id  radius  texture  perimeter  area  smoothness  compactness  symmetry  \
0   1      23       12        151   954       0.143        0.278     0.242   
1   2       9       13        133  1326       0.143        0.079     0.181   
2   3      21       27        130  1203       0.125        0.160     0.207   
3   4      14       16         78   386       0.070        0.284     0.260   
4   5       9       19        135  1297       0.141        0.133     0.181   

   fractal_dimension  
0              0.079  
1              0.057  
2              0.060  
3              0.097  
4              0.059

In [59]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x = scaler.fit_transform(x_data)

In [60]:
x

array([[0.        , 0.875     , 0.0625    , 0.825     , 0.44868735,
        1.        , 0.78175896, 0.63313609, 0.59090909],
       [0.01010101, 0.        , 0.125     , 0.675     , 0.67064439,
        1.        , 0.13355049, 0.27218935, 0.09090909],
       [0.02020202, 0.75      , 1.        , 0.65      , 0.59725537,
        0.75342466, 0.39739414, 0.4260355 , 0.15909091],
       [0.03030303, 0.3125    , 0.3125    , 0.21666667, 0.1097852 ,
        0.        , 0.80130293, 0.73964497, 1.        ],
       [0.04040404, 0.        , 0.5       , 0.69166667, 0.65334129,
        0.97260274, 0.30944625, 0.27218935, 0.13636364],
       [0.05050505, 1.        , 0.875     , 0.25833333, 0.16408115,
        0.79452055, 0.42996743, 0.43786982, 0.52272727],
       [0.06060606, 0.4375    , 0.9375    , 0.56666667, 0.5       ,
        0.34246575, 0.23127036, 0.26035503, 0.09090909],
       [0.07070707, 0.375     , 0.4375    , 0.31666667, 0.22434368,
        0.67123288, 0.41368078, 0.50295858, 0.5       ],


In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

method_names=[] 
method_scores=[]

In [62]:
x_train

array([[0.55555556, 0.5625    , 0.125     , 0.175     , 0.12350835,
        0.34246575, 0.05537459, 0.33727811, 0.13636364],
       [0.88888889, 0.125     , 0.        , 0.23333333, 0.1575179 ,
        0.24657534, 0.18241042, 0.34319527, 0.25      ],
       [0.26262626, 0.0625    , 0.8125    , 0.375     , 0.26431981,
        0.47945205, 0.48534202, 0.53254438, 0.36363636],
       [0.42424242, 0.125     , 0.        , 0.63333333, 0.53818616,
        0.28767123, 0.58957655, 0.56804734, 0.22727273],
       [0.6969697 , 0.5       , 0.625     , 0.24166667, 0.17959427,
        0.38356164, 0.04560261, 0.14201183, 0.09090909],
       [0.15151515, 0.8125    , 0.5       , 0.375     , 0.27267303,
        0.60273973, 0.39739414, 0.56213018, 0.40909091],
       [0.4040404 , 0.9375    , 0.3125    , 0.28333333, 0.21539379,
        0.16438356, 0.07166124, 0.25443787, 0.06818182],
       [0.96969697, 0.8125    , 0.1875    , 0.21666667, 0.14856802,
        0.47945205, 0.10749186, 0.32544379, 0.29545455],


In [63]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.85

In [64]:
dec_tree = DecisionTreeClassifier()
dec_tree.fit(x_train, y_train)
dec_tree.score(x_test, y_test)

0.7

In [65]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.85

In [66]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [69]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]):
    print(train_index, test_index)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
 32 33 34 35 36 37 38 39] [0 1 2 3 4 5 6 7]
[ 0  1  2  3  4  5  6  7 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
 32 33 34 35 36 37 38 39] [ 8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 24 25 26 27 28 29 30 31
 32 33 34 35 36 37 38 39] [16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 32 33 34 35 36 37 38 39] [24 25 26 27 28 29 30 31]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31] [32 33 34 35 36 37 38 39]


In [72]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [80]:
dec_tree.get_depth()

6

In [81]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_dectree = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=4), X_train, X_test, y_train, y_test))
    scores_dectree.append(get_score(DecisionTreeClassifier(max_depth= 6), X_train, X_test, y_train, y_test))  
    

In [82]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [83]:
scores_dectree

[0.6410684474123539, 0.7646076794657763, 0.7195325542570952]

In [84]:
scores_rf

[0.8380634390651085, 0.8363939899833055, 0.8313856427378965]

<h2 style='color:purple'>cross_val_score function</h2>

In [85]:
from sklearn.model_selection import cross_val_score

In [86]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [87]:
cross_val_score(DecisionTreeClassifier(max_depth= 6), digits.data, digits.target,cv=3)

array([0.65275459, 0.76460768, 0.71452421])

In [88]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92821369, 0.95325543, 0.92654424])

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [89]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8898137802607078

In [90]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9332153941651148

In [91]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9437833643699566

In [92]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9504624456859092

<b>Leave One Out Cross Validation<b>

In [100]:
from sklearn.model_selection import LeaveOneOut

from sklearn.model_selection import cross_val_score
loo = LeaveOneOut()
x = Cancer['fractal_dimension'].values.reshape(-1,1)
y = Cancer['compactness'].values.reshape(-1,1)
loo.get_n_splits(x)

100

In [101]:
print(loo)

LeaveOneOut()


In [103]:
for train_index, test_index in loo.split(x):
...     print("TRAIN:", train_index, "TEST:", test_index)
...     x_train, x_test = x[train_index], x[test_index]
...     y_train, y_test = y[train_index], y[test_index]
...     print(x_train, x_test, y_train, y_test)

TRAIN: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] TEST: [0]
[[0.057]
 [0.06 ]
 [0.097]
 [0.059]
 [0.076]
 [0.057]
 [0.075]
 [0.074]
 [0.082]
 [0.057]
 [0.061]
 [0.078]
 [0.053]
 [0.077]
 [0.071]
 [0.059]
 [0.074]
 [0.054]
 [0.058]
 [0.068]
 [0.069]
 [0.07 ]
 [0.053]
 [0.063]
 [0.074]
 [0.069]
 [0.057]
 [0.065]
 [0.061]
 [0.062]
 [0.078]
 [0.064]
 [0.063]
 [0.065]
 [0.057]
 [0.061]
 [0.059]
 [0.055]
 [0.064]
 [0.056]
 [0.069]
 [0.063]
 [0.068]
 [0.062]
 [0.06 ]
 [0.065]
 [0.068]
 [0.06 ]
 [0.057]
 [0.059]
 [0.06 ]
 [0.061]
 [0.063]
 [0.057]
 [0.059]
 [0.06 ]
 [0.068]
 [0.055]
 [0.072]
 [0.07 ]
 [0.068]
 [0.073]
 [0.07 ]
 [0.066]
 [0.067]
 [0.069]
 [0.057]
 [0.08 ]
 [0.057]
 [0.055]
 [0.09 ]
 [0.065]
 [0.066]
 [0.059]
 [0.054]
 [0.0

 [0.064]] [[0.072]] [[0.278]
 [0.079]
 [0.16 ]
 [0.284]
 [0.133]
 [0.17 ]
 [0.109]
 [0.165]
 [0.193]
 [0.24 ]
 [0.067]
 [0.129]
 [0.246]
 [0.1  ]
 [0.229]
 [0.16 ]
 [0.072]
 [0.202]
 [0.103]
 [0.081]
 [0.127]
 [0.065]
 [0.214]
 [0.102]
 [0.146]
 [0.228]
 [0.187]
 [0.107]
 [0.17 ]
 [0.116]
 [0.189]
 [0.152]
 [0.15 ]
 [0.172]
 [0.156]
 [0.134]
 [0.11 ]
 [0.038]
 [0.051]
 [0.126]
 [0.06 ]
 [0.122]
 [0.219]
 [0.144]
 [0.105]
 [0.169]
 [0.059]
 [0.123]
 [0.091]
 [0.077]
 [0.05 ]
 [0.061]
 [0.048]
 [0.149]
 [0.071]
 [0.055]
 [0.127]
 [0.137]
 [0.038]
 [0.081]
 [0.09 ]
 [0.201]
 [0.088]
 [0.126]
 [0.148]
 [0.078]
 [0.047]
 [0.141]
 [0.052]
 [0.103]
 [0.153]
 [0.183]
 [0.128]
 [0.068]
 [0.084]
 [0.105]
 [0.215]
 [0.345]
 [0.095]
 [0.094]
 [0.154]
 [0.267]
 [0.179]
 [0.072]
 [0.105]
 [0.099]
 [0.121]
 [0.094]
 [0.134]
 [0.086]
 [0.104]
 [0.051]
 [0.082]
 [0.155]
 [0.131]
 [0.071]
 [0.053]
 [0.075]
 [0.114]] [[0.053]]
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 2